
openapi: 3.0.3
info:
  title: DELF Assistant API (Vercel)
  version: "1.0.0"
servers:
  - url: https://YOUR_VERCEL_URL
paths:
  /api/delf/score:
    post:
      summary: Calcule les scores CO/CE/PE et génère un DOCX de commentaires
      operationId: delfScore
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/DelfRequest"
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/DelfResponse"
components:
  schemas:
    ItemKey:
      type: object
      properties: { q: {type: integer}, correct: {}, points: {type: number} }
      required: [q, correct, points]
    ExerciseKey:
      type: array
      items: { $ref: "#/components/schemas/ItemKey" }
    Cle:
      type: object
      properties:
        CO: { type: object, additionalProperties: { $ref: "#/components/schemas/ExerciseKey" } }
        CE: { type: object, additionalProperties: { $ref: "#/components/schemas/ExerciseKey" } }
    Reponses:
      type: object
      properties:
        CO: { type: object, additionalProperties: { type: object } }
        CE: { type: object, additionalProperties: { type: object } }
    PE:
      type: object
      properties:
        tache: { type: number }
        adequation: { type: number }
        lexique: { type: number }
        syntax_grammaire: { type: number }
        orthographe_ponctuation: { type: number }
    Meta:
      type: object
      properties: { nom_candidat: {type: string}, date: {type: string}, niveau: {type: string} }
    DelfRequest:
      type: object
      properties:
        niveau: { type: string, enum: [A1, A2, B1, B2] }
        public: { type: string, enum: [tp, junior, pro] }
        sujet: { type: integer }
        co_ecoutes: { type: integer, default: 2 }
        cle: { $ref: "#/components/schemas/Cle" }
        reponses: { $ref: "#/components/schemas/Reponses" }
        pe: { $ref: "#/components/schemas/PE" }
        meta: { $ref: "#/components/schemas/Meta" }
      required: [niveau, sujet, cle, reponses]
    DelfResponse:
      type: object
      properties:
        scores:
          type: object
          properties:
            CO: { type: object }
            CE: { type: object }
            PE: { type: object, nullable: true }
            total_hors_PO: { type: number }
        documents:
          type: object
          properties:
            commentaires_filename: { type: string }
            commentaires_docx_base64: { type: string }
